### ISSUE TITLE
About footer component detached from bottom of the page

### ISSUE THREAD

**Issue by dmvktr** [dmvktr/space-r-react#2]
After the initial about feature merge, the about section does not stick to the bottom of the page

**Comment by NorbertRuff** [comment]
Nice catch @dmvktr ! On the other pages it had to be fixed too.

 My approach with the grid rows set with percentages was not great so I changed it. 

Issue fixed with commit: cf9e12c5a4cd0cef81412a0ed36e768367b82c51 and commit: 57d8f8ff8781b2cd68cf1eb0a2ebb64a17e947b7

**Comment by dmvktr** [comment]
Thanks for the quick patch and heads-up @NorbertRuff ! The general fix worked like a charm. The attached Pull request #3 can also be closed now.
